' " https://plantuml.com/sequence-diagram  https://plantuml.com/class-diagram"

@startuml cases
package "Model" #F1f1f1{

    VillagerList o-->"0..*" Villager : villagers 
    ' PersonalPoints o--> "1" Villager : villager this shit is not working \/ this is
    Villager o--> "1" PersonalPoints : personalPoints
    Trade o--> "1"  Villager : villager 
    ' ^^^ idk if this is correct
    ' PersonalPoints *--> "1 " MyDate : date
    Perosnal points --> "
    Villager o--> "1" Date : date
    TaskList o--> "0..*" Task : tasks
    Cloverville --> "1" VillagerList : allVillagers
    Cloverville --> "1" TaskList : allTasks
    TradeList o--> "0..*" Trade : trades
    ClovervilleModelManager ..> MyFileHandler
    ClovervilleModelManager ..> Cloverville
    Cloverville --> "1" TradeList : allTrades
    Trade *--> "1" Date : completeDate

    class Villager{
        - ID : int
        - name : String
        - hasBoost : boolean
    
        + Villager(id : int, name : String, personalPoints : int, hasBoost : boolean)
        + setId(id : int) : void
        + getId() : int
        + setName(name : String) : void
        + getName() : String

    }
    
    class VillagerList{
        + addVillager(villagers : Villager) : void
        + removeVillager(villagers : Villager) : void
        + getVillager(index : int) : Villager  
        + getVillager(name : String) : Villager  
        + getAllVillagers() : Villager[]
    }
    
    class PersonalPoints{
        - personalPoints : int
    
        + setPoints(int personalPoints) : void
        + getPoints() : int
        + awardPoints() : void
        + resetPoints() : void  
        + calculateBoost() : double
        + awardBoost() : void
    }
    
    class greenPoints{
        - greenPoints : int
        - pointGoal : int
    
        + setGoal() : void
        + getGoal() : int
        + resetPeriod : Date
        + resetPoints() : void
        + addPoints() : void
        + getPoints() : int
    }
    
    class Date{
        - day : int
        - month : int
        - year : int
        - currDay : int
        - currMonth : int
        - currYear : int
    
        + Date(day : int, month : int, year : int)
        + setDate(day : int, month : int, year : int) : void
        + copy() : Date
        + today() : Date
    }
    
    class Trade{
        - name : String
        - description : String
        - trader : Villager
        - tradee : Villager
        - pointCost : int
        - tradeOffer : String
    
        + Trade(name : String, description : String, trader : Villager, pointCost : int)
        + Trade(name : String, description : String, trader : Villager, tradeOffer : String)
        + setTrader() : void
        + getTrader() : Villager
        + setTradee() : void
        + getTradee() : Villager
        + geStringtName() : String
        + getDescription() : String
    }
    class TradeList
    {

        + addTrade() : void
        + removeTrade() : void
        + getTrade(index int) : Trade
        + getAllTrades() : Trade
    }
    
    class TaskList{
        - tasks : Task
        
        + addTask() : void
        + removeTask() : void
    }
    
    class Task{
        - name : String
        - type : String
        - amountPoints : int
    
        + completeTask : boolean
    }
    Class Cloverville
    {

    }
    Class ClovervilleModelManager
    {
        + loadData() : void
        + saveData() : void
    }

}
    



package "view"#ababab{
    StartGUI ..> ViewHandler
    VillagerViewController --> "1" ViewHandler 
    TradeViewController --> "1" ViewHandler
    RunGUI ..> StartGUI
    ViewHandler --> "1" ClovervilleModelManager

    Class StartGUI
    {
        
    }
    Class ViewHandler
    {
        + main(args String) : void
    }
    Class TradeViewController
    {

    }
    Class VillagerViewController
    {

    }
    class RunGUI
    {
        +main(args : String) : void
    }
    'points and editing 
}
package "utils" #d3d3d3
{
    class MyFileHandler
    {

        + saveToFile(fileName : String) : void
        + loadFromFile(fileName : String) : void
    }
}