package model;

import java.util.ArrayList;

/**
 * The class that handles all operations for the Cloverville system
 * @author Loke Hansen
 * @author Victor Tonu
 * @author Adam Terelak
 */
public class ClovervilleModelManager {

    private final Cloverville cloverville;

    /**
     * Creates a manager with a Cloverville instance that is fresh
     */
    public ClovervilleModelManager() {
        cloverville = new Cloverville();
    }

    /**
     * Returns all residents
     * @return List of residents
     */
    public ArrayList<Resident> getAllResidents() {
        return cloverville.getResidentList().getAllResidents();
    }

    /**
     * Adds a new resident with an ID that is generated by plussing 1 to the list of residents
     * @param firstName Residents first name
     * @param lastName  Residents last name
     */
    public void addResident(String firstName, String lastName) {
        ArrayList<Resident> residents = cloverville.getResidentList().getAllResidents();
        int nextId = 1;
        if (!residents.isEmpty()) {
            nextId = residents.get(residents.size() - 1).getId() + 1;
        }
        Resident v = new Resident(nextId, firstName, lastName);
        cloverville.getResidentList().addResident(v);
    }

    /**
     * Returns all tasks
     * @return List of tasks
     */
    public ArrayList<Task> getTaskList() {
        return cloverville.getTaskList().getAllTasks();
    }
    /**
     * Gets the status of the boost
     * @param residentid    need to get the residents id to identify which resident
     * used instead of name since that is editable
     */

    public boolean getBoostStatus(int residentId) {
        Resident v = cloverville.getResidentList().getResidentById(residentId);
        if (v != null) {
            return v.getHasBoost();
        }
        return false;
        
    }

    /**
     * Adds a new task of the apropriate type, green or communal
     * @param name        Task name
     * @param type        Task type
     * @param points      Points award
     * @param description Description of the task
     */
    public void addTask(String name, String type, int points, String description) {
        Task task;

        if (type != null && type.toLowerCase().contains("green")) {
            task = new GreenActions(name, type, points);
        } else {
            task = new CommunityTasks(name, type, points);
        }
        task.setDescription(description);
        cloverville.getTaskList().addTask(task);
    }

    /**
     * Updates a task
     * @param task        Task to update
     * @param name        New name
     * @param description New description
     * @param type        New type label
     * @param points      New points value
     */
    public void updateTask(Task task, String name, String description, String type, int points) {
        task.setName(name);
        task.setDescription(description);
        task.setType(type);
        task.setPoints(points);
    }

    /**
     * Returns all trades
     * @return List of trades
     */
    public ArrayList<Trade> getTradeList() {
        // return new ArrayList<Trade>(trades);
        return cloverville.getTradeList().getAllTrades();
    }

    /**
     * Adds a trade
     * @param name        Trade title
     * @param description Trade description
     * @param trader      Resident offering the trade
     * @param pointCost   Cost in personal points
     */
    public void addTrade(String name, String description, Resident trader, int pointCost) {
        cloverville.getTradeList().addTrade(new Trade(name, description, trader, pointCost));
    }

    /**
     * Awards personal points to a resident, again used id to identify resident
     * @param residentId Residents ID
     * @param points     Points to add
     */
    public void awardPointsToResident(int residentId, int points) {
        Resident v = cloverville.getResidentList().getResidentById(residentId);
        if (v != null) {
            v.addPersonalPoints(points);
        }
    }
    /**
     * Awards a boost to resident
     * @param residentId    Residents Id
     */
    public void awardBoostToResident(int residentId) {
        Resident v = cloverville.getResidentList().getResidentById(residentId);
        cloverville.awardBoost(v);
    }
    /** 
     * Resets the personal points of each villager
     */

    public void resetAllPersonalPoints() {
        for (Resident resident : getAllResidents()) {
            resident.resetPersonalPoints();
        }
    }

    /**
     * Adds green points toward the community pool
     * @param points Points to add
     */
    public void addGreenPoints(int points) {
        cloverville.getGreenPoints().addPoints(points);
    }

    /**
     * Gets green points
     * @return Green points
     */
    public int getGreenPoints() {
        return cloverville.getGreenPoints().getPoints();
    }
    /** 
     * gets the green point object
     * @return green point object
     */
    public GreenPoints getGreenPointsObject() {
        return cloverville.getGreenPoints();
    }

    /** 
     * gets the text of what the reward is
     * @return the text of what the reward is
     */
    public String getCommunityReward() {
        return cloverville.getGreenPoints().getCommunityReward();
    }

    /**
     * Gets current green points goal
     * @return Goal value
     */
    public int getGreenPointsGoal() {
        return cloverville.getGreenPoints().getGoal();
    }
    /**
     * Sets the point goal for the community to get the reward
     * @param goal  the goal to get the reward
     */

    public void setGreenPointsGoal(int goal) {
        cloverville.getGreenPoints().setGoal(goal);
    }
    /**
    * Imports a list of residents into the Cloverville class.
    * @param residents the list of residents to import
    */

    public void importResidents(ArrayList<Resident> residents) {
        for (Resident resident : residents) {
            cloverville.getResidentList().addResident(resident);
        }
    }
    /**
    * Imports a list of tasks into the Cloverville class.
    * @param tasks the list of tasks to import
    */
    public void importTasks(ArrayList<Task> tasks) {
        for (Task task : tasks) {
            cloverville.getTaskList().addTask(task);
        }
    }
    /**
    * Imports a list of trades into the Cloverville class.
    * @param trades the list of trades to import
    */
    public void importTrades(ArrayList<Trade> trades) {
        for (Trade trade : trades) {
            cloverville.getTradeList().addTrade(trade);
        }
    }
    /**
     * Imports green points into the Cloverville class.
    * @param gp the GreenPoints instance to import
    */
    public void importGreenPoints(GreenPoints gp) {
        if (gp != null) {
            cloverville.setGreenPoints(gp);
        }
    }
    /** 
    * removes the task from the list
    * @param task  the task selected
    */
    public void removeTask(Task task) {
        cloverville.getTaskList().removeTask(task);
    }
    /**
    * removes the trade from the list
    * @param trade the trade selected
    */
    public void removeTrade(Trade trade) {
        cloverville.getTradeList().removeTrade(trade);
    }
    /**
     * removes the resident from the list
     * @param resident  resident selected
     */
    public void removeResident(Resident resident) {
        cloverville.getResidentList().removeResident(resident);
    }
}

